inherit_from: .rubocop_todo.yml
require: rubocop-rspec

AllCops:
  DisplayCopNames: true
  Exclude:
    - '.internal_test_app/**/*'

Rails:
  Enabled: true

Layout/LineLength:
  Max: 185

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - 'spec/**/*'
    - 'lib/generators/**/*'
