notifications:
  email: false

rvm:
  - 2.6.3
  - 2.5.5

notifications:
  irc: "irc.freenode.org#blacklight"
  email:
      - blacklight-commits@googlegroups.com
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

jdk: openjdk11
